// API-008: manifesto de cobertura (docs/api-arquitetura.md §4 e §14). As 357
// operações de docs/api-inventario.json, cada uma apontando para:
//   - o id da ação do registro que a cobre (ex.: 'meta.acoes.listar');
//   - 'never:<motivo>', o que a API não faz de propósito (§13);
//   - 'pending:API-0NN', o card que vai cobrir.
// Gerado do inventário em 07/10/2026; desde então, cada card troca as suas
// linhas de 'pending' para o id da ação. coverage.test.ts confere a paridade
// com o inventário e que todo id existe no registro; o API-063 exige zero
// 'pending'. Alguns ids do inventário têm '|' ou espaço: valem como estão.

/** pending:API-0NN, never:<motivo> ou o id de uma ação do registro. */
export type CoverageTarget = string

export const COVERAGE: Readonly<Record<string, CoverageTarget>> = {
  'account.ai_credentials.set': 'never:legado de segredo de IA, removido no API-032',
  'account.api_tokens.create': 'never:gestão de tokens só em Configurações → API; um token nunca cria ou amplia tokens',
  'account.api_tokens.list': 'never:gestão de tokens só em Configurações → API; um token nunca cria ou amplia tokens',
  'account.api_tokens.revoke': 'never:gestão de tokens só em Configurações → API; um token nunca cria ou amplia tokens',
  'account.daily_login.check': 'never:furaria o re-login diário (REL-007)',
  'account.email.change': 'never:conta sem segundo fator (senha, MFA, e-mail, login/logout) fica só na tela',
  'account.last_login.record': 'never:furaria o re-login diário (REL-007)',
  'account.mfa.enroll': 'never:conta sem segundo fator (senha, MFA, e-mail, login/logout) fica só na tela',
  'account.mfa.list_factors': 'never:conta sem segundo fator (senha, MFA, e-mail, login/logout) fica só na tela',
  'account.mfa.unenroll': 'never:conta sem segundo fator (senha, MFA, e-mail, login/logout) fica só na tela',
  'account.mfa.verify_challenge': 'never:conta sem segundo fator (senha, MFA, e-mail, login/logout) fica só na tela',
  'account.password.change': 'never:conta sem segundo fator (senha, MFA, e-mail, login/logout) fica só na tela',
  'account.password.reset_complete': 'never:conta sem segundo fator (senha, MFA, e-mail, login/logout) fica só na tela',
  'account.password.reset_request': 'never:conta sem segundo fator (senha, MFA, e-mail, login/logout) fica só na tela',
  'account.session.signin_signup_signout': 'never:conta sem segundo fator (senha, MFA, e-mail, login/logout) fica só na tela',
  'admin.audit.list': 'pending:API-057',
  'admin.backups.create': 'never:escrita de administração fica só na tela, com MFA (decisão 4)',
  'admin.backups.delete': 'never:escrita de administração fica só na tela, com MFA (decisão 4)',
  'admin.backups.list': 'pending:API-057',
  'admin.backups.overview': 'pending:API-057',
  'admin.backups.restore': 'never:escrita de administração fica só na tela, com MFA (decisão 4)',
  'admin.backups.run_auto_if_due': 'never:escrita de administração fica só na tela, com MFA (decisão 4)',
  'admin.backups.settings.get': 'pending:API-057',
  'admin.backups.settings.toggle_auto': 'never:escrita de administração fica só na tela, com MFA (decisão 4)',
  'admin.backups.validate': 'never:escrita de administração fica só na tela, com MFA (decisão 4)',
  'admin.invites.delete_used_or_expired': 'never:escrita de administração fica só na tela, com MFA (decisão 4)',
  'admin.invites.generate': 'never:escrita de administração fica só na tela, com MFA (decisão 4)',
  'admin.invites.list_all': 'pending:API-057',
  'admin.invites.quotas.adjust': 'never:escrita de administração fica só na tela, com MFA (decisão 4)',
  'admin.invites.quotas.list': 'pending:API-057',
  'admin.invites.revoke_unused': 'never:escrita de administração fica só na tela, com MFA (decisão 4)',
  'admin.observability.status_and_test_event': 'never:escrita de administração fica só na tela, com MFA (decisão 4)',
  'admin.users.ban': 'never:escrita de administração fica só na tela, com MFA (decisão 4)',
  'admin.users.delete': 'never:escrita de administração fica só na tela, com MFA (decisão 4)',
  'admin.users.delete_profile_row (latent, no UI)': 'never:escrita de administração fica só na tela, com MFA (decisão 4)',
  'admin.users.last_sign_in': 'never:escrita de administração fica só na tela, com MFA (decisão 4)',
  'admin.users.list': 'pending:API-057',
  'admin.users.revoke_sessions': 'never:escrita de administração fica só na tela, com MFA (decisão 4)',
  'admin.users.search': 'pending:API-057',
  'admin.users.send_password_reset': 'never:escrita de administração fica só na tela, com MFA (decisão 4)',
  'admin.users.set_role': 'never:escrita de administração fica só na tela, com MFA (decisão 4)',
  'admin.users.unban': 'never:escrita de administração fica só na tela, com MFA (decisão 4)',
  'admin.users.update_profile_fields (latent, no UI)': 'never:escrita de administração fica só na tela, com MFA (decisão 4)',
  'api.auth.rate_limit': 'never:interno do gateway (resolução de token e limites)',
  'api.auth.resolve_token': 'never:interno do gateway (resolução de token e limites)',
  'api.meta.actions': 'meta.acoes.listar',
  'api.tokens.create': 'never:gestão de tokens só em Configurações → API; um token nunca cria ou amplia tokens',
  'api.tokens.list': 'never:gestão de tokens só em Configurações → API; um token nunca cria ou amplia tokens',
  'api.tokens.manage': 'never:gestão de tokens só em Configurações → API; um token nunca cria ou amplia tokens',
  'api.tokens.revoke': 'never:gestão de tokens só em Configurações → API; um token nunca cria ou amplia tokens',
  'dashboard.home.get': 'pending:API-059',
  'dashboard.quick_create_page': 'pending:API-038',
  'dashboard.summary.read': 'pending:API-059',
  'documents.drawings.export_local': 'never:renderização no cliente; o conteúdo sai pelas leituras e pelo CSV',
  'documents.drawings.get': 'pending:API-054',
  'documents.drawings.save': 'pending:API-054',
  'documents.drawings.subscribe': 'never:tempo real, presença e estado de tela não são API',
  'documents.export.pdf': 'never:renderização no cliente; o conteúdo sai pelas leituras e pelo CSV',
  'documents.files.resolve_note_image': 'pending:API-044',
  'documents.files.upload_note_image': 'pending:API-044',
  'documents.graph.get': 'pending:API-059',
  'documents.navigation.local_state': 'never:tempo real, presença e estado de tela não são API',
  'documents.notes.embed_project_card': 'pending:API-044',
  'documents.notes.ensure_row': 'pending:API-044',
  'documents.notes.get': 'pending:API-044',
  'documents.notes.insert_diagram_block': 'pending:API-044',
  'documents.notes.save': 'pending:API-044',
  'documents.notes.subscribe': 'never:tempo real, presença e estado de tela não são API',
  'documents.pages.change_type': 'pending:API-038',
  'documents.pages.create': 'pending:API-038',
  'documents.pages.delete': 'pending:API-038',
  'documents.pages.get': 'pending:API-038',
  'documents.pages.list': 'pending:API-038',
  'documents.pages.list_favorites_recent': 'pending:API-038',
  'documents.pages.move': 'pending:API-038',
  'documents.pages.rename': 'pending:API-038',
  'documents.pages.reorder': 'pending:API-038',
  'documents.pages.search_titles': 'pending:API-038',
  'documents.pages.set_icon': 'pending:API-038',
  'documents.pages.toggle_favorite': 'pending:API-038',
  'documents.presence.heartbeat': 'never:tempo real, presença e estado de tela não são API',
  'documents.presence.leave': 'never:tempo real, presença e estado de tela não são API',
  'documents.presence.list': 'never:tempo real, presença e estado de tela não são API',
  'documents.shares.add': 'pending:API-050',
  'documents.shares.change_role': 'pending:API-050',
  'documents.shares.is_shared': 'pending:API-050',
  'documents.shares.list': 'pending:API-050',
  'documents.shares.remove': 'pending:API-050',
  'documents.shares.search_users': 'pending:API-050',
  'documents.todos.create': 'pending:API-045',
  'documents.todos.delete': 'pending:API-045',
  'documents.todos.list': 'pending:API-045',
  'documents.todos.subscribe': 'never:tempo real, presença e estado de tela não são API',
  'documents.todos.update': 'pending:API-045',
  'finance.accounts.balances': 'pending:API-036',
  'finance.accounts.create': 'pending:API-036',
  'finance.accounts.delete': 'pending:API-036',
  'finance.accounts.list': 'pending:API-036',
  'finance.accounts.update': 'pending:API-036',
  'finance.budgets.auto_from_recurring': 'never:cron e rotinas internas do servidor',
  'finance.budgets.create': 'pending:API-046',
  'finance.budgets.delete': 'pending:API-046',
  'finance.budgets.list': 'pending:API-046',
  'finance.budgets.status': 'pending:API-046',
  'finance.budgets.update': 'pending:API-046',
  'finance.categories.bootstrap': 'pending:API-036',
  'finance.categories.create': 'pending:API-036',
  'finance.categories.delete': 'pending:API-036',
  'finance.categories.list': 'pending:API-036',
  'finance.categories.update': 'pending:API-036',
  'finance.dashboard.widget': 'pending:API-059',
  'finance.goals.contributions.create': 'pending:API-046',
  'finance.goals.contributions.delete': 'pending:API-046',
  'finance.goals.contributions.list': 'pending:API-046',
  'finance.goals.create': 'pending:API-046',
  'finance.goals.delete': 'pending:API-046',
  'finance.goals.list': 'pending:API-046',
  'finance.goals.set_status': 'pending:API-046',
  'finance.goals.shares.create': 'pending:API-056',
  'finance.goals.shares.delete': 'pending:API-056',
  'finance.goals.shares.list': 'pending:API-056',
  'finance.goals.update': 'pending:API-046',
  'finance.loans.approve': 'pending:API-060',
  'finance.loans.balance': 'pending:API-060',
  'finance.loans.borrowers.create': 'pending:API-060',
  'finance.loans.borrowers.delete': 'pending:API-060',
  'finance.loans.borrowers.link': 'pending:API-060',
  'finance.loans.borrowers.list': 'pending:API-060',
  'finance.loans.borrowers.unlink': 'pending:API-060',
  'finance.loans.borrowers.update': 'pending:API-060',
  'finance.loans.cancel_request': 'pending:API-060',
  'finance.loans.collaterals.create': 'pending:API-060',
  'finance.loans.collaterals.delete': 'pending:API-060',
  'finance.loans.collaterals.update': 'pending:API-060',
  'finance.loans.delete': 'pending:API-060',
  'finance.loans.files.delete': 'pending:API-060',
  'finance.loans.files.read': 'pending:API-060',
  'finance.loans.files.upload': 'pending:API-060',
  'finance.loans.list': 'pending:API-060',
  'finance.loans.payments.confirm': 'pending:API-060',
  'finance.loans.payments.delete': 'pending:API-060',
  'finance.loans.payments.record': 'pending:API-060',
  'finance.loans.payments.reject': 'pending:API-060',
  'finance.loans.payments.report': 'pending:API-060',
  'finance.loans.payments.update': 'pending:API-060',
  'finance.loans.reject': 'pending:API-060',
  'finance.loans.request': 'pending:API-060',
  'finance.loans.update': 'pending:API-060',
  'finance.preferences.dashboard_view': 'pending:API-041',
  'finance.projects.summary': 'pending:API-049',
  'finance.recurring.create': 'pending:API-047',
  'finance.recurring.delete': 'pending:API-047',
  'finance.recurring.entries.list': 'pending:API-047',
  'finance.recurring.entries.mark_paid': 'pending:API-047',
  'finance.recurring.entries.materialize': 'never:cron e rotinas internas do servidor',
  'finance.recurring.entries.skip': 'pending:API-047',
  'finance.recurring.list': 'pending:API-047',
  'finance.recurring.update': 'pending:API-047',
  'finance.reports.export_pdf': 'never:renderização no cliente; o conteúdo sai pelas leituras e pelo CSV',
  'finance.reports.network': 'pending:API-049',
  'finance.reports.overview': 'pending:API-049',
  'finance.reports.projects_summary': 'pending:API-049',
  'finance.reports.workspace_overview': 'pending:API-049',
  'finance.sharing.partner_profiles': 'pending:API-056',
  'finance.sharing.search_users': 'pending:API-050',
  'finance.statements.legacy': 'never:objeto legado sem uso',
  'finance.store.attachments.read': 'pending:API-048',
  'finance.store.attachments.remove': 'pending:API-052',
  'finance.store.attachments.upload': 'pending:API-052',
  'finance.store.customers.create': 'pending:API-052',
  'finance.store.customers.delete': 'pending:API-052',
  'finance.store.customers.list': 'pending:API-048',
  'finance.store.customers.update': 'pending:API-052',
  'finance.store.overview': 'pending:API-048',
  'finance.store.products.archive': 'pending:API-052',
  'finance.store.products.create': 'pending:API-052',
  'finance.store.products.delete': 'pending:API-052',
  'finance.store.products.get': 'pending:API-048',
  'finance.store.products.list': 'pending:API-048',
  'finance.store.products.update': 'pending:API-052',
  'finance.store.purchases.create': 'pending:API-052',
  'finance.store.purchases.delete': 'pending:API-052',
  'finance.store.purchases.generate_expense': 'pending:API-052',
  'finance.store.purchases.list': 'pending:API-048',
  'finance.store.purchases.set_status': 'pending:API-052',
  'finance.store.purchases.update': 'pending:API-052',
  'finance.store.sale_items.add': 'pending:API-052',
  'finance.store.sale_items.remove': 'pending:API-052',
  'finance.store.sale_items.update': 'pending:API-052',
  'finance.store.sales.create': 'pending:API-052',
  'finance.store.sales.delete': 'pending:API-052',
  'finance.store.sales.generate_income': 'pending:API-052',
  'finance.store.sales.list': 'pending:API-048',
  'finance.store.sales.set_status': 'pending:API-052',
  'finance.store.sales.update': 'pending:API-052',
  'finance.store.snapshot': 'pending:API-048',
  'finance.store.suppliers.create': 'pending:API-052',
  'finance.store.suppliers.list': 'pending:API-048',
  'finance.suppliers.create': 'pending:API-052',
  'finance.suppliers.list': 'pending:API-048',
  'finance.transactions.attach_receipt': 'pending:API-040',
  'finance.transactions.bulk_delete': 'pending:API-040',
  'finance.transactions.create': 'pending:API-040',
  'finance.transactions.delete': 'pending:API-040',
  'finance.transactions.export_csv': 'pending:API-040',
  'finance.transactions.history': 'pending:API-040',
  'finance.transactions.import_statement': 'pending:API-040',
  'finance.transactions.list': 'pending:API-040',
  'finance.transactions.update': 'pending:API-040',
  'finance.workspace.create': 'pending:API-056',
  'finance.workspace.delete': 'never:excluir o espaço só por sair_workspace',
  'finance.workspace.get': 'pending:API-056',
  'finance.workspace.invites.accept': 'pending:API-056',
  'finance.workspace.invites.create': 'pending:API-056',
  'finance.workspace.invites.decline': 'pending:API-056',
  'finance.workspace.invites.list_received': 'pending:API-056',
  'finance.workspace.leave': 'pending:API-056',
  'finance.workspace.members.remove': 'pending:API-056',
  'finance.workspace.rename': 'pending:API-056',
  'help.articles.browse': 'never:tempo real, presença e estado de tela não são API',
  'invites.generate': 'pending:API-042',
  'invites.mine.list': 'pending:API-042',
  'invites.slots.read': 'pending:API-042',
  'invites.validate': 'never:fluxo anônimo de cadastro com limite por IP',
  'notifications.delete': 'pending:API-042',
  'notifications.invite.respond': 'pending:API-056',
  'notifications.list': 'pending:API-042',
  'notifications.mark_all_read': 'pending:API-042',
  'notifications.mark_read': 'pending:API-042',
  'notifications.respond_workspace_invite': 'pending:API-056',
  'notifications.subscribe': 'never:tempo real, presença e estado de tela não são API',
  'notifications.unread_count': 'pending:API-042',
  'onboarding.tours.start_finish': 'never:tempo real, presença e estado de tela não são API',
  'profile.avatar.read': 'pending:API-041',
  'profile.avatar.remove': 'pending:API-041',
  'profile.avatar.upload': 'pending:API-041',
  'profile.me.read': 'pending:API-041',
  'profile.me.refresh': 'pending:API-041',
  'profile.me.update': 'pending:API-041',
  'profile.onboarding.mark_seen': 'pending:API-041',
  'profile.onboarding.start_tour': 'never:tempo real, presença e estado de tela não são API',
  'profile.preferences.finance_dashboard_view.set': 'pending:API-041',
  'profile.preferences.theme.set': 'pending:API-041',
  'projects.boards.create': 'pending:API-039',
  'projects.boards.delete': 'pending:API-039',
  'projects.boards.get': 'pending:API-039',
  'projects.boards.list': 'pending:API-019',
  'projects.boards.members.list': 'pending:API-039',
  'projects.boards.setup_flow': 'pending:API-019',
  'projects.boards.stats': 'pending:API-039',
  'projects.boards.update': 'pending:API-039',
  'projects.cards.assign': 'pending:API-043',
  'projects.cards.attachments.remove': 'pending:API-043',
  'projects.cards.attachments.upload': 'pending:API-043',
  'projects.cards.attachments.view': 'pending:API-043',
  'projects.cards.auto_schedule': 'pending:API-055',
  'projects.cards.block': 'pending:API-019',
  'projects.cards.check_items': 'pending:API-019',
  'projects.cards.checklist.manage': 'pending:API-043',
  'projects.cards.complete': 'pending:API-019',
  'projects.cards.copy_to_note': 'pending:API-044',
  'projects.cards.create': 'pending:API-043',
  'projects.cards.delete': 'pending:API-043',
  'projects.cards.export_markdown': 'pending:API-043',
  'projects.cards.get': 'pending:API-019',
  'projects.cards.labels.manage': 'pending:API-043',
  'projects.cards.link_page': 'pending:API-043',
  'projects.cards.links.manage': 'pending:API-043',
  'projects.cards.list': 'pending:API-019',
  'projects.cards.move': 'pending:API-043',
  'projects.cards.note_phase': 'pending:API-019',
  'projects.cards.pick': 'pending:API-019',
  'projects.cards.relations.manage': 'pending:API-043',
  'projects.cards.release': 'pending:API-019',
  'projects.cards.reschedule': 'pending:API-043',
  'projects.cards.search': 'pending:API-043',
  'projects.cards.set_completed': 'pending:API-043',
  'projects.cards.update': 'pending:API-043',
  'projects.cards.validate': 'pending:API-019',
  'projects.columns.create': 'pending:API-039',
  'projects.columns.delete': 'pending:API-039',
  'projects.columns.list': 'pending:API-039',
  'projects.columns.reorder': 'pending:API-039',
  'projects.columns.update': 'pending:API-039',
  'projects.dashboard.cards': 'pending:API-059',
  'projects.import.backlog_markdown': 'pending:API-055',
  'projects.queue.block': 'pending:API-019',
  'projects.queue.complete': 'pending:API-019',
  'projects.queue.enqueue': 'pending:API-019',
  'projects.queue.list': 'pending:API-019',
  'projects.queue.move': 'pending:API-019',
  'projects.queue.next': 'pending:API-019',
  'projects.queue.note': 'pending:API-019',
  'projects.queue.release': 'pending:API-019',
  'projects.queue.remove': 'pending:API-019',
  'projects.queue.reprioritize': 'pending:API-019',
  'projects.queue.start': 'pending:API-019',
  'projects.queue.start_batch': 'pending:API-019',
  'projects.queue.validate': 'pending:API-019',
  'projects.shares.add': 'pending:API-050',
  'projects.shares.list': 'pending:API-050',
  'projects.shares.remove': 'pending:API-050',
  'projects.shares.search_users': 'pending:API-050',
  'projects.shares.update_role': 'pending:API-050',
  'quick_notes.create': 'pending:API-051',
  'quick_notes.delete': 'pending:API-051',
  'quick_notes.link_item.add': 'pending:API-051',
  'quick_notes.link_item.open': 'never:tempo real, presença e estado de tela não são API',
  'quick_notes.link_item.remove': 'pending:API-051',
  'quick_notes.links.add': 'pending:API-051',
  'quick_notes.links.remove': 'pending:API-051',
  'quick_notes.list': 'pending:API-051',
  'quick_notes.update': 'pending:API-051',
  'quick_notes.update_color': 'pending:API-051',
  'quick_notes.update_content': 'pending:API-051',
  'study.cards.append_markdown': 'pending:API-034',
  'study.cards.checkpoints.add|toggle|edit|remove': 'pending:API-034',
  'study.cards.checkpoints.edit': 'pending:API-034',
  'study.cards.checkpoints.toggle': 'pending:API-053',
  'study.cards.create': 'pending:API-034',
  'study.cards.delete': 'pending:API-034',
  'study.cards.list': 'pending:API-034',
  'study.cards.quiz.answer': 'pending:API-053',
  'study.cards.quiz.answer|reset': 'pending:API-053',
  'study.cards.quiz.reset': 'pending:API-053',
  'study.cards.reschedule': 'pending:API-034',
  'study.cards.resources.add|remove': 'pending:API-034',
  'study.cards.resources.edit': 'pending:API-034',
  'study.cards.update': 'pending:API-034',
  'study.logs.create': 'pending:API-053',
  'study.logs.delete': 'pending:API-053',
  'study.logs.list': 'pending:API-053',
  'study.lookup_cache.prune': 'never:objeto legado sem uso',
  'study.markdown.parse': 'pending:API-034',
  'study.overview.get': 'pending:API-034',
  'study.planning.get': 'pending:API-034',
  'study.prompt.build': 'pending:API-053',
  'study.stats.get': 'pending:API-034',
  'study.topics.create': 'pending:API-034',
  'study.topics.delete': 'pending:API-034',
  'study.topics.get': 'pending:API-034',
  'study.topics.import': 'pending:API-034',
  'study.topics.list': 'pending:API-034',
  'study.topics.set_status': 'pending:API-034',
  'study.topics.update': 'pending:API-034',
  'system.cron.history_prune': 'never:cron e rotinas internas do servidor',
  'system.cron.site_backup_auto': 'never:cron e rotinas internas do servidor',
  'system.cron.stale_backup_alert': 'never:cron e rotinas internas do servidor',
  'system.rate_limit.check': 'never:cron e rotinas internas do servidor',
  'todos.create': 'pending:API-045',
  'todos.delete': 'pending:API-045',
  'todos.list_by_page': 'pending:API-045',
  'todos.list_mine': 'pending:API-045',
  'todos.subscribe': 'never:tempo real, presença e estado de tela não são API',
  'todos.toggle_complete': 'pending:API-045',
  'todos.update': 'pending:API-045',
  'ui.workspace_mode.switch': 'never:tempo real, presença e estado de tela não são API',
}

const PENDING = /^pending:(API-\d{3})$/
const NEVER = /^never:\S/

/** Problemas do manifesto: alvo em formato inválido ou id de ação que não existe. */
export function coverageProblems(coverage: Readonly<Record<string, CoverageTarget>>, actionIds: ReadonlySet<string>): string[] {
  return Object.entries(coverage).flatMap(([op, target]) => {
    if (PENDING.test(target) || NEVER.test(target)) return []
    if (target.startsWith('pending:') || target.startsWith('never:')) return [`${op}: alvo mal formado (${target})`]
    return actionIds.has(target) ? [] : [`${op}: ação inexistente no registro (${target})`]
  })
}

/** Quantas operações ainda esperam cada card (só os pendentes). */
export function pendingByCard(coverage: Readonly<Record<string, CoverageTarget>>): Record<string, number> {
  const out: Record<string, number> = {}
  for (const target of Object.values(coverage)) {
    const card = PENDING.exec(target)?.[1]
    if (card) out[card] = (out[card] ?? 0) + 1
  }
  return out
}
