-- ⚠️ MIGRAÇÃO NEUTRALIZADA EM 2026-07-29 — NÃO RESTAURAR O CORPO ORIGINAL. ⚠️
--
-- O corpo original convertia as colunas financeiras de numeric(15,2) (reais)
-- para bigint (centavos), multiplicando os valores existentes por 100:
--
--   alter table public.finance_transactions
--     alter column amount type bigint using round(amount * 100)::bigint;
--   -- idem para: finance_accounts.initial_balance,
--   --            finance_budgets.amount_limit,
--   --            finance_goals.target_amount,
--   --            finance_goal_contributions.amount,
--   --            finance_recurring.amount,
--   --            finance_recurring_entries.amount
--
-- Por que foi esvaziada:
--   Esta migração NUNCA foi aplicada no projeto remoto (nhfftophadasiezrzlsv)
--   e não consta em supabase_migrations.schema_migrations. Verificado em
--   2026-07-29: as sete colunas acima ainda são `numeric` no remoto, mas o
--   app já grava CENTAVOS (inteiros) nelas desde que o código toCents/
--   fromCents entrou em produção. Executar o corpo original agora — por
--   exemplo via `supabase db push` — multiplicaria TODOS os valores
--   financeiros por 100 (transações, contas, orçamentos, metas,
--   contribuições, recorrentes).
--
-- Com o corpo vazio, aplicar esta migração é um no-op seguro em qualquer
-- ambiente: `supabase db push` apenas registra a versão. Em bancos criados
-- do zero as colunas permanecem numeric, igual ao remoto — consistente.
--
-- Se um dia quiserem de fato migrar o TIPO das colunas para bigint, criem uma
-- NOVA migração usando `alter column ... type bigint using round(col)::bigint`
-- (SEM multiplicar por 100 — os valores já estão em centavos).

select 1; -- no-op intencional
